version: '3'
services:
  php:
    image: php:7.2-cli-alpine3.8
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
  composer:
    image: composer:1.7.2
    volumes:
      - "./:/app"
    command: install
